twig:
    globals:
        vk_client: '%env(VK_CLIENT_ID)%'
        vk_secret: '%env(VK_SECRET_KEY)%'
        domain: '%env(DOMAIN)%'
        port: '%env(PORT)%'
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig']
